AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Puzzdra Monster Rating on Sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

# custom
Parameters:
  Env:
    Type: String
    Default: Prd
    AllowedValues:
      - Dev
      - Prd

Resources:
  GetMonsterRatingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /monsters/{no}
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_TABLE_NAME: !Ref MonsterRatings
          MONSTER_SOURCE_DATA_JSON_URL: ""
          GAME8_MONSTER_URLS_FILE: ""
          AWS_SAM_LOCAL: ""
      Policies:
        - DynamoDBCrudPolicy:  # LambdaにDynamoDBへのアクセス権限を付与
            TableName: !Ref MonsterRatings
  MonsterRatings:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}MonsterRatings"
      AttributeDefinitions:
        - AttributeName: "No"
          AttributeType: S
      KeySchema:
        - AttributeName: "No"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetMonsterRatingAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/monsters/{no}"
  GetMonsterRatingFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GetMonsterRatingFunction.Arn
  GetMonsterRatingFunctionIamRole:
    Description: "Implicit IAM Role created for GetMonsterRating function"
    Value: !GetAtt GetMonsterRatingFunctionRole.Arn
  DynamoDBTableName:
    Description: "Name of the DynamoDB table created"
    Value: !Ref MonsterRatings
